import { AuthProvider } from "./AuthContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Caveat, Reem_Kufi_Fun } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import { CartProvider } from "./CartContext";
import { LanguageProvider } from "./LanguageContext";
import LanguageWrapper from "./LanguageWrapper";

/* -------- Base Fonts (Body) -------- */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* -------- Draw / Handwritten Fonts -------- */
const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-draw-en",
});

const reemKufi = Reem_Kufi_Fun({
  subsets: ["arabic"],
  weight: ["400", "600", "700"],
  variable: "--font-draw-ar",
});

export const metadata: Metadata = {
  title: "قَمَرْ",
  description: "Generated by Youssef Hashish",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${caveat.variable}
          ${reemKufi.variable}
          antialiased
        `}
      >
        <LanguageProvider>
          <AuthProvider>
            <CartProvider>
              <LanguageWrapper>
                <Navbar />
                {children}
                <Toaster position="top-center" />
              </LanguageWrapper>
            </CartProvider>
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
